[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.11.0"
  NPM_FLAGS = "--no-audit --no-fund"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8080
  targetPort = 8080

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.razorpay.com https://*.leafletjs.com; style-src 'self' 'unsafe-inline' https://*.leafletjs.com; img-src 'self' data: https: blob:; connect-src 'self' https://*.supabase.co https://*.razorpay.com https://*.leafletjs.com; frame-src 'self' https://*.razorpay.com;"