services:
  - type: web
    name: parkmaster
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 22.11.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
